### ISSUE TITLE
Cubbit cask is out of date

### ISSUE THREAD

**Issue by faelin** [cubbit/homebrew-tap#3]
Attempting to install Cubbit via homebrew installs version 9.1.4, leading to a warning from Apple:
![Screen Shot 2022-04-06 at 11 41 24 AM](https://user-images.githubusercontent.com/8279240/162014663-f914ed3f-213c-4387-b322-b793a0b78ccf.png)

**Comment by marmos91** [comment]
Hi @faelin, and thank you for the report. The version is indeed outdated. @lurenzsgp can you provide us with the latest stable version?

**Comment by lurenzsgp** [comment]
Hi @faelin, thanks for the report. It is a known issue that we have fixed in the actual internal version. It's visible only during the installation and the fix will be released with the next release

**Comment by lurenzsgp** [comment]
The formula has been updated with https://github.com/cubbit/homebrew-tap/pull/4. That app version is not affected by the notarization issue.
